package com.Zalvi.entity;
// Generated Jan 10, 2020 11:36:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,catalog="db_zalvi"
)
public class Item  implements java.io.Serializable {


     private int idItem;
     private String nama;
     private byte jenis;
     private int stock;
     private int harga;
     private byte urutan;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public Item() {
    }

	
    public Item(int idItem, String nama, byte jenis, int stock, int harga, byte urutan) {
        this.idItem = idItem;
        this.nama = nama;
        this.jenis = jenis;
        this.stock = stock;
        this.harga = harga;
        this.urutan = urutan;
    }
    public Item(int idItem, String nama, byte jenis, int stock, int harga, byte urutan, Set<Transaksi> transaksis) {
       this.idItem = idItem;
       this.nama = nama;
       this.jenis = jenis;
       this.stock = stock;
       this.harga = harga;
       this.urutan = urutan;
       this.transaksis = transaksis;
    }
   
     @Id 

    
    @Column(name="idItem", unique=true, nullable=false)
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }

    
    @Column(name="nama", nullable=false, length=45)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="jenis", nullable=false)
    public byte getJenis() {
        return this.jenis;
    }
    
    public void setJenis(byte jenis) {
        this.jenis = jenis;
    }

    
    @Column(name="stock", nullable=false)
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }

    
    @Column(name="harga", nullable=false)
    public int getHarga() {
        return this.harga;
    }
    
    public void setHarga(int harga) {
        this.harga = harga;
    }

    
    @Column(name="urutan", nullable=false)
    public byte getUrutan() {
        return this.urutan;
    }
    
    public void setUrutan(byte urutan) {
        this.urutan = urutan;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="item")
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


