package com.Zalvi.entity;
// Generated Jan 10, 2020 11:36:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaksi generated by hbm2java
 */
@Entity
@Table(name="transaksi"
    ,catalog="db_zalvi"
)
public class Transaksi  implements java.io.Serializable {


     private Integer idTransaksi;
     private Item item;
     private User user;
     private Date tanggalTransaksi;
     private String namaItem;

    public Transaksi() {
    }

    public Transaksi(Item item, User user, Date tanggalTransaksi, String namaItem) {
       this.item = item;
       this.user = user;
       this.tanggalTransaksi = tanggalTransaksi;
       this.namaItem = namaItem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTransaksi", unique=true, nullable=false)
    public Integer getIdTransaksi() {
        return this.idTransaksi;
    }
    
    public void setIdTransaksi(Integer idTransaksi) {
        this.idTransaksi = idTransaksi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Item_idItem", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_idUser", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="tanggal_transaksi", nullable=false, length=10)
    public Date getTanggalTransaksi() {
        return this.tanggalTransaksi;
    }
    
    public void setTanggalTransaksi(Date tanggalTransaksi) {
        this.tanggalTransaksi = tanggalTransaksi;
    }

    
    @Column(name="nama_item", nullable=false, length=45)
    public String getNamaItem() {
        return this.namaItem;
    }
    
    public void setNamaItem(String namaItem) {
        this.namaItem = namaItem;
    }




}


