package com.Zalvi.entity;
// Generated Jan 10, 2020 11:36:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="db_zalvi"
)
public class User  implements java.io.Serializable {


     private int idUser;
     private int money;
     private String nama;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public User() {
    }

	
    public User(int idUser, int money, String nama) {
        this.idUser = idUser;
        this.money = money;
        this.nama = nama;
    }
    public User(int idUser, int money, String nama, Set<Transaksi> transaksis) {
       this.idUser = idUser;
       this.money = money;
       this.nama = nama;
       this.transaksis = transaksis;
    }
   
     @Id 

    
    @Column(name="idUser", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="money", nullable=false)
    public int getMoney() {
        return this.money;
    }
    
    public void setMoney(int money) {
        this.money = money;
    }

    
    @Column(name="Nama", nullable=false, length=45)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


